const createSwedenMapPalette = ({
  background,
  swedenAreaFill,
  landcoverForest,
  landcoverPark,
  landcoverBase,
  landuseUrban,
  waterFill,
  waterwayLine,
  roadsCasing,
  roadsMotorway,
  roadsPrimary,
  roadsLocal,
  roadLabel,
  roadLabelHalo,
  buildingsResidential,
  buildingsCommercial,
  buildingsIndustrial,
  buildingsPublic,
  buildingsLow,
  buildingsHighLow,
  buildingsHighMid,
  buildingsHighTall,
  skyColor,
  skyHorizonColor,
  fogColor
}) =>
  Object.freeze({
    background,
    swedenAreaFill,
    swedenAreaFillOpacity: 0.9,
    swedenBorder: "#5a9fd4",
    swedenBorderOpacity: 0.82,
    landcoverForest,
    landcoverPark,
    landcoverBase,
    landcoverOpacity: 0.76,
    landuseUrban,
    landuseUrbanOpacity: 0.38,
    waterFill,
    waterFillOpacity: 0.84,
    waterwayLine,
    roadsCasing,
    roadsCasingOpacity: 0.88,
    roadsMotorway,
    roadsPrimary,
    roadsLocal,
    roadsOpacity: 0.92,
    roadLabel,
    roadLabelHalo,
    buildingsResidential,
    buildingsCommercial,
    buildingsIndustrial,
    buildingsPublic,
    buildingsLow,
    buildingsHighLow,
    buildingsHighMid,
    buildingsHighTall,
    skyColor,
    skyHorizonColor,
    fogColor
  });

export const SWEDEN_MAP_PALETTE = createSwedenMapPalette({
  background: "#dce8f2",
  swedenAreaFill: "#c8daea",
  landcoverForest: "#5fa87a",
  landcoverPark: "#78bf8e",
  landcoverBase: "#6baa7e",
  landuseUrban: "#b8c8d8",
  waterFill: "#6aafe0",
  waterwayLine: "#7ec4f0",
  roadsCasing: "#ffffff",
  roadsMotorway: "#e8924a",
  roadsPrimary: "#eaad5c",
  roadsLocal: "#e8eff5",
  roadLabel: "#2a3e52",
  roadLabelHalo: "#ffffffdd",
  buildingsResidential: "#e4dbd0",
  buildingsCommercial: "#d0d8e2",
  buildingsIndustrial: "#a8a098",
  buildingsPublic: "#d4c8e4",
  buildingsLow: "#eee6dc",
  buildingsHighLow: "#e2d8cc",
  buildingsHighMid: "#ccd4de",
  buildingsHighTall: "#b8c6d8",
  skyColor: "#a8c8e4",
  skyHorizonColor: "#dceaf4",
  fogColor: "#c8dae8"
});

export const SWEDEN_MAP_NIGHT_PALETTE = createSwedenMapPalette({
  background: "#0f1a28",
  swedenAreaFill: "#152436",
  landcoverForest: "#1e4a38",
  landcoverPark: "#265a42",
  landcoverBase: "#224e3a",
  landuseUrban: "#2a3a4e",
  waterFill: "#1a4a6e",
  waterwayLine: "#2a5a82",
  roadsCasing: "#1e2e42",
  roadsMotorway: "#c47830",
  roadsPrimary: "#b88840",
  roadsLocal: "#3a4e62",
  roadLabel: "#c8d8ea",
  roadLabelHalo: "#0f1a28cc",
  buildingsResidential: "#6e5e50",
  buildingsCommercial: "#4e6478",
  buildingsIndustrial: "#565048",
  buildingsPublic: "#5e5070",
  buildingsLow: "#5a4e44",
  buildingsHighLow: "#625648",
  buildingsHighMid: "#4a5e72",
  buildingsHighTall: "#3e5268",
  skyColor: "#0a1420",
  skyHorizonColor: "#1a2840",
  fogColor: "#121e30"
});

export const MAP_PALETTES = Object.freeze({
  day: SWEDEN_MAP_PALETTE,
  night: SWEDEN_MAP_NIGHT_PALETTE
});
